sudo: required
services:
  - docker

before_install:
  - docker build -t lc13lc13/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lc13lc13/react-test npm test -- --coverage

after_success:
  - docker build -t lc13lc13/multi-client ./client
  - docker build -t lc13lc13/multi-nginx ./nginx
  - docker build -t lc13lc13/multi-server ./server
  - docker build -t lc13lc13/multi-worker ./worker
# Login to docer CLI in a single command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lc13lc13/multi-client
  - docker push lc13lc13/multi-nginx
  - docker push lc13lc13/multi-server
  - docker push lc13lc13/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-452114670412
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY